In [5]:
!pip install numpy

In [7]:
import numpy as np


In [9]:
#1-d array
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [10]:
type(arr1)

numpy.ndarray

In [6]:
arr3=np.zeros((2,3))
arr3
print(arr3.ndim)

NameError: name 'np' is not defined

In [7]:
print(arr3.ndim)

NameError: name 'arr3' is not defined

In [6]:
import numpy as np 
arr3=np.array([1,2,3,4,5,6,7])
print(arr3[1:5])

[2 3 4 5]


In [10]:
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[4:])

[5 6 7]


In [11]:
arr7=np.array([1,2,3,4,5,6,7])
3print(arr7[1:5:2])

[2 4]


In [12]:
#shape of an array: shape that returms a tuple with each index having the number of corresponding 
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [13]:
#reshape from 1-D to 2-D 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
#reshape from 1-D to 3-D 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
#iterating arrays
import numpy as np
arr=np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [7]:
#numpy joining array 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1 , arr2))
print(arr)

[1 2 3 4 5 6]


In [13]:
arr1=np.array([[1,2] , [3,4]])
arr2=np.array([[5,6] , [7,8]])
arr=np.concatenate((arr1, arr2) , axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [16]:
#generate a random integer from 0 to 100:
from numpy import random 
x=random.randint(100)
print(x)

68


In [17]:
x=random.rand()
print(x)

0.1606318383323483


In [18]:
from numpy import random
x=random.randint(100,size=(6))
print(x)

[51 33 64 22 95 66]


In [19]:
x=random.rand(3,5)
print(x)

[[0.47753206 0.08301081 0.55063594 0.09244954 0.0273054 ]
 [0.22209013 0.24381085 0.115385   0.35932554 0.37387191]
 [0.05105569 0.66425279 0.52896678 0.63198617 0.12480414]]
